[book]
title = "Discovery"
description = "Discover the world of microcontrollers through Rust"
author = "Rust Embedded Resources Team"
language = "en"

[output.html]
git-repository-url = "https://github.com/rust-embedded/discovery/"
